// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
//
// PLACEHOLDER — substitua este arquivo executando:
//
//   dart pub global activate flutterfire_cli
//   flutterfire configure
//
// O comando vai detectar suas plataformas (android, ios, web) e gerar a
// versão final do DefaultFirebaseOptions com as chaves reais do projeto
// Firebase. Veja CLAUDE.md → "Configurar Firebase".

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions ainda não configurado para esta plataforma. '
          'Rode `flutterfire configure` para gerar este arquivo.',
        );
    }
  }

  // ────────────────────────────────────────────────────────────────────
  // Substitua todos os valores abaixo por chaves reais (via flutterfire
  // configure). Os valores presentes são apenas placeholders para o
  // projeto compilar — *NÃO* funcionam em runtime.
  // ────────────────────────────────────────────────────────────────────

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'PLACEHOLDER_WEB_API_KEY',
    appId: 'PLACEHOLDER_WEB_APP_ID',
    messagingSenderId: 'PLACEHOLDER_SENDER_ID',
    projectId: 'trovata-placeholder',
    authDomain: 'trovata-placeholder.firebaseapp.com',
    storageBucket: 'trovata-placeholder.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'PLACEHOLDER_ANDROID_API_KEY',
    appId: 'PLACEHOLDER_ANDROID_APP_ID',
    messagingSenderId: 'PLACEHOLDER_SENDER_ID',
    projectId: 'trovata-placeholder',
    storageBucket: 'trovata-placeholder.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'PLACEHOLDER_IOS_API_KEY',
    appId: 'PLACEHOLDER_IOS_APP_ID',
    messagingSenderId: 'PLACEHOLDER_SENDER_ID',
    projectId: 'trovata-placeholder',
    storageBucket: 'trovata-placeholder.appspot.com',
    iosBundleId: 'br.com.trovata.view3d',
  );
}
