// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
//
// PLACEHOLDER — substitua este arquivo executando:
//
//   dart pub global activate flutterfire_cli
//   flutterfire configure
//
// O comando vai detectar suas plataformas (android, ios, web) e gerar a
// versão final do DefaultFirebaseOptions com as chaves reais do projeto
// Firebase. Veja CLAUDE.md → "Configurar Firebase".

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions ainda não configurado para esta plataforma. '
          'Rode `flutterfire configure` para gerar este arquivo.',
        );
    }
  }

  // ────────────────────────────────────────────────────────────────────
  // Substitua todos os valores abaixo por chaves reais (via flutterfire
  // configure). Os valores presentes são apenas placeholders para o
  // projeto compilar — *NÃO* funcionam em runtime.
  // ────────────────────────────────────────────────────────────────────

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'PLACEHOLDER_WEB_API_KEY',
    appId: 'PLACEHOLDER_WEB_APP_ID',
    messagingSenderId: 'PLACEHOLDER_SENDER_ID',
    projectId: 'view3d-placeholder',
    authDomain: 'view3d-placeholder.firebaseapp.com',
    storageBucket: 'view3d-placeholder.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnO8tExcPSUrmnEVD_A80vEM5IqE1W12Q',
    appId: '1:930876458445:android:69d2710a8209d4ba3b3084',
    messagingSenderId: '930876458445',
    projectId: 'view3d-caf85',
    storageBucket: 'view3d-caf85.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlXBsD1RVAzSs7pVNYTwixd4DCPB5wd_g',
    appId: '1:930876458445:ios:847532e3bb5b6b763b3084',
    messagingSenderId: '930876458445',
    projectId: 'view3d-caf85',
    storageBucket: 'view3d-caf85.firebasestorage.app',
    iosBundleId: 'app.showcas3d.view3d',
  );

}